[tools]
go = "latest"
deno = "latest"
pnpm = "latest"
node = "latest"
rust = "latest"
zoxide = "latest"
fzf = "latest"
watchexec = "latest"
bat = "latest"
neovim = "latest"
fd = "latest"
python = "latest"
zellij = "latest"
uv = "latest"
java = "latest"
