---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: shire home

showStats: true
background:
  # Light theme
  #image: https://images.unsplash.com/photo-1635776063328-153b13e3c245?q=80&w=1632&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D

  # Dark theme
  image: https://images.unsplash.com/photo-1717810135803-830d2c4e0d43?q=80&w=928&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  brightness: 50
  blur: md
cardBlur: sm

theme: dark
color: gray

hideVersion: true
iconStyle: theme
disableCollapse: true

layout:
  Services:
    icon: mdi-server
    style: column
